stages:
  - build
  - test
  - docker-build
  - docker-push
  - deploy

# ------------------------------
# 1. BUILD
# ------------------------------
build_job:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build

# ------------------------------
# 2. TEST
# ------------------------------
test_job:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm test

# ------------------------------
# 3. DOCKER BUILD
# ------------------------------
docker_build:
  stage: docker-build
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_NAME:latest $REGISTRY_URL/$IMAGE_NAME:latest

# ------------------------------
# 4. DOCKER PUSH
# ------------------------------
docker_push:
  stage: docker-push
  script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin
    - docker push $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_URL/$IMAGE_NAME:latest

# ------------------------------
# 5. DEPLOY LOCAL
# ------------------------------
deploy_local:
  stage: deploy
  script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin
    - docker rm -f tp-gitlab-ci || true
    - docker pull $REGISTRY_URL/$IMAGE_NAME:latest
    - docker run -d --name tp-gitlab-ci -p 3000:3000 $REGISTRY_URL/$IMAGE_NAME:latest
