stages:
  - build
  - test
  - docker
  - deploy

# ------------------------------
# 1. BUILD (Node image)
# ------------------------------
build_job:
  stage: build
  image: node:20
  tags: [node]
  script:
    - npm ci
    - npm test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1h

# ------------------------------
# 2. TEST (Node image)
# ------------------------------
test_job:
  stage: test
  image: node:20
  tags: [node]
  script:
    - npm ci
    - npm test

# ------------------------------
# 3. DOCKER BUILD + PUSH (Host Docker)
# ------------------------------
docker_build_push:
  stage: docker
  tags: [dockerx]
  script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin

    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $REGISTRY_URL/$IMAGE_NAME:latest
    - docker tag $IMAGE_NAME:latest $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA

    - docker push $REGISTRY_URL/$IMAGE_NAME:latest
    - docker push $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA

# ------------------------------
# 4. DEPLOY LOCAL
# ------------------------------
deploy_local:
  stage: deploy
  tags: [dockerx]
  script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY_URL -u "$NEXUS_USERNAME" --password-stdin

    - docker rm -f tp-gitlab-ci || true
    - docker pull $REGISTRY_URL/$IMAGE_NAME:latest
    - docker run -d --name tp-gitlab-ci -p 3000:3000 $REGISTRY_URL/$IMAGE_NAME:latest
